FROM paritytech/ci-linux:production as build

WORKDIR /code
COPY . .
#No need Rust flags as updated to latest QEMU
#RUN RUSTFLAGS="-C target-cpu=x86-64" cargo build --release
#ENV RUSTFLAGS="-C target-feature=-sse4.1"
#ENV RUSTFLAGS="-C target-cpu=x86-64"

RUN cargo build --release

FROM ubuntu:20.04
WORKDIR /node

# Copy the node binary.
COPY --from=build /code/target/release/node-template .

# Install root certs, see: https://github.com/paritytech/substrate/issues/9984
RUN apt update && \
    apt install -y ca-certificates && \
    update-ca-certificates && \
    apt remove ca-certificates -y && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 30333 9933 9944 9615 
# Exposing unsafe RPC methods is needed for testing but should not be done in
# production.
#ENTRYPOINT ["./node-template"]
#CMD echo "Node Template Hello World"
#CMD [ "./node-template", "--dev", "--ws-external", "--rpc-methods=Unsafe" ]

#Reference1:https://substrate.stackexchange.com/questions/4643/build-a-docker-file-image-for-my-new-pallet
#Reference2:https://github.com/perun-network/perun-polkadot-node/blob/f0a29200bed5d2e4ec6fcb0ce8ae121f9124ff5a/node/Dockerfile
#Reference3:https://github.com/paritytech/polkadot/blob/master/scripts/ci/dockerfiles/polkadot/polkadot_builder.Dockerfile